# Generated by Django 5.0.2 on 2025-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_assignment_options_remove_assignment_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='completed_date',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
