# Generated by Django 5.0.2 on 2025-04-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_subtask'),
        ('tasks', '0003_remove_assignment_completed_date_and_more'),
    ]

    operations = [
    ]
